#!/bin/bash

# memo:
# dashboard_entry=()
# dashboard_enable=()
# dashboard_reply=()
# dashboard_reply_help=()

# ordering: 
# /usr/local/lib/bim/
# /usr/local/share/bim/modules
# /etc/bim/modules/
# /home/${USER}/.bim/modules

PREFIX="${0%/bin/*}"
export PREFIX
BIMMODULES="${PREFIX}/lib/bim ${PREFIX}/share/bim/modules /etc/bim/modules ${HOME}/.bim/modules ./lib ./modules"

###################################
# lookup and load modules 
for searchpath in ${BIMMODULES}
do
	if [[ -d "${searchpath}" ]]
	then
		for module in "${searchpath}/"*
		do
			if [[ -d "${module}" ]]
			then
				for part in "${module}/"*.bim
				do
					if [[ -f "${part}" ]]
					then
						. "${part}"
					fi
				done
			else
				if [[ "${module}" = *.bim ]]
				then
					. "${module}"
				fi
			fi
		done
	fi
done

#############################
# start 
menuname="${1}"
menuname=${menuname:=dashboard}
shift
"${menuname}" "${@}"


